---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 'Avec l"interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures), vous pouvez configurer rapidement le service iSCSI sur une machine virtuelle de stockage (SVM), provisionner une LUN et mettre la LUN disponible à l"aide d"un initiateur iSCSI sur un ordinateur hôte ESXi.' 
---
= Présentation de la configuration iSCSI pour ESXi à l'aide de VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avec l'interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures), vous pouvez configurer rapidement le service iSCSI sur une machine virtuelle de stockage (SVM), provisionner une LUN et mettre la LUN disponible à l'aide d'un initiateur iSCSI sur un ordinateur hôte ESXi.

Utiliser cette procédure si :

* Vous utilisez l'initiateur logiciel iSCSI ESXi natif sur ESXi 5.x.
* Vous n'utilisez pas l'authentification CHAP pour iSCSI.
* Une version prise en charge de Virtual Storage Console pour VMware vSphere (VSC) permet de configurer les paramètres de stockage de votre hôte ESX.
+
** VSC fait partie du produit depuis la version 7.0 de VSC https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Outils ONTAP pour VMware vSphere"^] Appliance virtuelle, qui comprend VSC, le fournisseur vStorage APIs for Storage Awareness (VASA) et l'outil Storage Replication adapter (SRA) pour les fonctionnalités VMware vSphere.
** Assurez-vous de vérifier le https://imt.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^] Pour vérifier la compatibilité entre vos versions actuelles de ONTAP et VSC.


* Votre réseau utilise l'adressage IPv4.
* Vous souhaitez attribuer des adresses à des interfaces logiques à l'aide de l'une des méthodes suivantes :
+
** Automatiquement à partir d'un sous-réseau que vous définissez
** Manuellement, à l'aide d'une adresse sélectionnée à partir d'un sous-réseau existant
** Manuellement, à l'aide d'une adresse qui sera ajoutée à un sous-réseau existant


* Vous disposez d'au moins deux ports Ethernet haut débit (1 GbE minimum, 10 GbE recommandé) disponibles sur chaque nœud du cluster.
+
Ports UTA2 intégrés (également appelés `CNA`) les ports sont configurables. Vous configurez ces ports dans l'interface de ligne de commande ONTAP, ce processus n'est pas couvert par sa procédure.

+
Voir link:https://docs.netapp.com/us-en/ontap/networking/index.html["Gestion de réseau"^] Pour configurer le contrôle de flux du port Ethernet à l'aide de l'interface de ligne de commande.

* Vous ne configurez pas le démarrage SAN iSCSI.
* Vous fournissons un stockage aux machines virtuelles via l'hyperviseur ESXi et n'exécutant pas d'initiateur iSCSI au sein de cette machine virtuelle.


Pour plus d'informations, voir https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["Tr-4597 : VMware vSphere pour ONTAP"^] Et de la documentation relative à la version de VSC.
