---
permalink: iscsi-config-esxi/task_verifying_that_iscsi_fc_configuration_is_supported.html 
sidebar: sidebar 
keywords: reliable, operation, verify, iscsi, configuration, support, verify that the iscsi configuration is supported 
summary: 'Pour un fonctionnement fiable, vous devez vérifier que l"intégralité de la configuration iSCSI est prise en charge.' 
---
= Vérifiez que la configuration iSCSI est prise en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour un fonctionnement fiable, vous devez vérifier que l'intégralité de la configuration iSCSI est prise en charge.

.Étapes
. Accédez à la matrice d'interopérabilité pour vérifier que vous disposez d'une combinaison de composants prise en charge :
+
** Logiciel ONTAP
** Architecture UC de l'ordinateur hôte (pour serveurs en rack standard)
** Modèle de lame de processeur spécifique (pour serveurs lames)
** Protocole de stockage (iSCSI)
** Version du système d'exploitation ESXi
** Type et version du système d'exploitation invité
** Virtual Storage Console (VSC) pour le logiciel VMware vSphere
** Version de Windows Server pour exécuter VSC


. Cliquez sur le nom de la configuration sélectionnée.
+
Les détails de cette configuration s'affichent dans la fenêtre Détails de la configuration.

. Vérifiez les informations dans les onglets suivants :
+
** Remarques
+
Le répertorie les alertes et informations importantes spécifiques à votre configuration.

** Politiques et lignes directrices
+
Présente des recommandations générales pour toutes les configurations SAN.




