---
sidebar: sidebar 
permalink: reference_legal_notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc. 
---
= Mentions légales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

http://www.netapp.com/us/legal/copyright.aspx[]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

https://www.netapp.com/us/media/patents-page.pdf[]



== Politique de confidentialité

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Source ouverte

Fournit des informations sur les droits d'auteur tiers et les licences utilisées dans ce produit.

link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876856["Notification relative à ONTAP 9.9.1"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2873871["Notification relative à ONTAP 9.8"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2860921["Avis pour ONTAP 9.7"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2855145["Avis pour ONTAP 9.6"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2850702["Avis pour ONTAP 9.5"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2844310["Avis pour ONTAP 9.4"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2839209["Avis pour ONTAP 9.3"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2702054["Avis pour ONTAP 9.2"]
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2516795["Avis pour ONTAP 9.1"]
