---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: System Manager permet de créer, modifier et gérer des partages. 
---
= Gérez les partages avec System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 


Vous pouvez utiliser ONTAP System Manager classique (disponible dans ONTAP 9.7 et versions antérieures) pour créer, modifier et gérer des partages.



== Créer un partage CIFS

Vous pouvez utiliser System Manager pour créer un partage CIFS qui vous permet de spécifier le dossier, qtree ou volume auquel les utilisateurs CIFS peuvent accéder.

.Avant de commencer
Vous devez avoir installé la licence CIFS avant de configurer et de démarrer CIFS.

.Étapes
. Cliquez sur *Storage* > *Shares*.
. Dans le menu déroulant du champ *SVM*, sélectionnez la SVM sur laquelle vous souhaitez créer un partage CIFS.
. Cliquez sur *Créer un partage*.
. Dans la fenêtre *Créer un partage*, cliquez sur *Parcourir*, puis sélectionnez le dossier, le qtree ou le volume qui doit être partagé.
. Spécifiez un nom pour le nouveau partage CIFS.
. *Facultatif:* cochez la case *Activer la disponibilité continue pour Hyper-V et SQL* pour permettre aux clients qui prennent en charge SMB 3.0 et versions ultérieures d'ouvrir les fichiers de manière persistante pendant la continuité de l'activité.
+
Les fichiers ouverts à l'aide de cette option sont protégés contre les événements perturbateur tels que le basculement, le rétablissement et la migration de LIF.

+
Depuis la version System Manager 9.6, la disponibilité continue est prise en charge pour les volumes FlexGroup.

. Cochez la case *crypter les données lors de l'accès à ce partage* pour activer le cryptage SMB 3.0.
. Fournissez une description ou un commentaire pour le partage, puis cliquez sur *Créer*.


.Résultats
Le partage CIFS est créé avec les autorisations d'accès définies sur « contrôle total pour tous » dans le groupe.



== Arrêtez l'accès au partage

System Manager peut être utilisé pour arrêter un partage lorsque vous souhaitez supprimer l'accès réseau partagé à un dossier, qtree ou volume.

.Avant de commencer
Vous devez avoir installé la licence CIFS.

.Étapes
. Cliquez sur *Storage* > *Shares*.
. Dans le menu déroulant du champ *SVM*, sélectionnez la SVM sur laquelle réside le partage CIFS que vous souhaitez arrêter.
. Dans la liste des partages, sélectionnez le partage que vous souhaitez arrêter le partage, puis cliquez sur *Arrêter le partage*.
. Cochez la case de confirmation, puis cliquez sur *Stop*.
. Vérifiez que le partage n'est plus répertorié dans la fenêtre *partages*.




== Créer des partages de répertoire personnel

Vous pouvez utiliser System Manager pour créer un partage de home Directory et gérer les chemins de recherche des home Directory.

.Avant de commencer
Le protocole CIFS doit être configuré et démarré.

.Étapes
. Cliquez sur *Storage* > *Shares*.
. Cliquez sur *Create Home Directory*, puis fournissez les informations de motif qui déterminent la manière dont un utilisateur est mappé à un répertoire.
. Cliquez sur *Créer*.
. Vérifiez que le répertoire personnel que vous avez créé est répertorié dans la fenêtre *partages*.




== Modifier les paramètres de partage

Vous pouvez utiliser System Manager pour modifier les paramètres d'un partage, tels que les paramètres du lien symbolique, les autorisations d'accès de partage des utilisateurs ou groupes et le type d'accès au partage. Vous pouvez également activer ou désactiver la disponibilité continue d'un partage sur Hyper-V et activer ou désactiver l'énumération basée sur l'accès (ABE). Depuis la version System Manager 9.6, la disponibilité continue est prise en charge pour les volumes FlexGroup.

.Étapes
. Cliquez sur *Storage* > *Shares*.
. Sélectionnez le partage que vous souhaitez modifier dans la liste des partages, puis cliquez sur *Modifier*.
. Dans la boîte de dialogue *Modifier les paramètres de partage*, modifiez les paramètres de partage comme requis :
+
.. Dans l'onglet *général*, activez la disponibilité continue d'un partage sur Hyper-V.
+
L'activation de la disponibilité continue permet à SMB 3.0 et aux clients qui prennent en charge SMB 3.0 d'ouvrir les fichiers de manière persistante lors de la continuité de l'activité. Les fichiers ouverts de manière persistante sont protégés contre les événements perturbateurs tels que le basculement, le retour et la migration de LIF.

.. Dans l'onglet *permissions*, ajoutez des utilisateurs ou des groupes, puis attribuez des autorisations pour spécifier le type d'accès.
.. Dans l'onglet *Options*, sélectionnez les options requises.


. Cliquez sur *Enregistrer et fermer*.
. Vérifiez les modifications que vous avez apportées au partage sélectionné dans la fenêtre *partages*.




== Comment ONTAP rend possible les répertoires locaux dynamiques

Les home directories ONTAP vous permettent de configurer un partage SMB qui correspond à différents répertoires en fonction de l'utilisateur qui se connecte à celui-ci et d'un ensemble de variables. Au lieu de créer des partages distincts pour chaque utilisateur, vous pouvez configurer un partage avec quelques paramètres de home Directory afin de définir la relation d'un utilisateur entre un point d'entrée (le partage) et le home Directory (un répertoire sur la SVM).

Un utilisateur connecté en tant qu'utilisateur invité ne dispose pas d'un répertoire personnel et ne peut pas accéder aux répertoires d'accueil d'autres utilisateurs. Il existe quatre variables qui déterminent la manière dont un utilisateur est mappé à un répertoire :

* *Nom de partage*
+
Il s'agit du nom du partage que vous créez et auquel l'utilisateur se connecte. Vous devez définir la propriété du répertoire personnel pour ce partage.

+
Le nom du partage peut utiliser les noms dynamiques suivants :

+
** `%w` (Nom d'utilisateur Windows de l'utilisateur)
** `%d` (Nom de domaine Windows de l'utilisateur)
** `%u` (Nom d'utilisateur UNIX mappé de l'utilisateur)


+
Pour que le nom du partage soit unique dans tous les répertoires d'accueil, le nom du partage doit contenir soit/`%w` ou le `%u` variable. Le nom du partage peut contenir les deux `%d` et le/`%w` variable (par exemple, `%d`/`%w`), ou le nom du partage peut contenir une partie statique et une partie variable (par exemple, home_/`%w`).

* *Chemin de partage*
+
Il s'agit du chemin relatif, défini par le partage, et donc associé à l'un des noms de partage, qui est ajouté à chaque chemin de recherche pour générer le chemin d'accès complet du home Directory de l'utilisateur, à partir de la racine de la SVM. Il peut être statique (par exemple, `home`), dynamique (par exemple, `%w`), ou une combinaison des deux (par exemple, `eng/%w`).

* *Chemins de recherche*
+
Il s'agit de l'ensemble des chemins absolus depuis la racine du SVM que vous spécifiez qui dirigent la recherche ONTAP pour les répertoires locaux. Vous pouvez spécifier un ou plusieurs chemins de recherche à l'aide du `vserver cifs home-directory search-path add` commande. Si vous spécifiez plusieurs chemins de recherche, ONTAP les essaie dans l'ordre spécifié jusqu'à ce qu'il trouve un chemin valide.

* *Répertoire*
+
Il s'agit du répertoire de base de l'utilisateur que vous créez pour l'utilisateur. Le nom du répertoire est généralement le nom de l'utilisateur. Vous devez créer le répertoire personnel dans l'un des répertoires définis par les chemins de recherche.



Prenons l'exemple de la configuration suivante :

* Utilisateur : John Smith
* Domaine utilisateur : acme
* Nom d'utilisateur: Jsmith
* Nom du SVM : vs1
* Nom de partage du répertoire de base n°1 : Home_ `%w` - chemin de partage : `%w`
* Nom de partage du répertoire racine #2 : `%w` - chemin de partage : `%d/%w`
* Chemin de recherche n°1 : `/vol0home/home`
* Chemin de recherche n°2 : `/vol1home/home`
* Chemin de recherche n°3 : `/vol2home/home`
* Home Directory : `/vol1home/home/jsmith`


Scénario 1 : l'utilisateur se connecte à `\\vs1\home_jsmith`. Ceci correspond au premier nom de partage du répertoire racine et génère le chemin relatif `jsmith`. ONTAP recherche désormais un répertoire nommé `jsmith` en vérifiant chaque chemin de recherche dans l'ordre suivant :

* `/vol0home/home/jsmith` n'existe pas ; passer au chemin de recherche n°2.
* `/vol1home/home/jsmith` existe ; par conséquent, le chemin de recherche #3 n'est pas coché ; l'utilisateur est maintenant connecté à son répertoire de base.


Scénario 2 : l'utilisateur se connecte à `\\vs1\jsmith`. Ceci correspond au deuxième nom de partage du répertoire de base et génère le chemin relatif `acme/jsmith`. ONTAP recherche désormais un répertoire nommé `acme/jsmith` en vérifiant chaque chemin de recherche dans l'ordre suivant :

* `/vol0home/home/acme/jsmith` n'existe pas ; passer au chemin de recherche n°2.
* `/vol1home/home/acme/jsmith` n'existe pas ; passer au chemin de recherche #3.
* `/vol2home/home/acme/jsmith` n'existe pas ; le répertoire personnel n'existe pas ; la connexion échoue donc.




== Fenêtre partages

Vous pouvez utiliser la fenêtre partages pour gérer vos partages et afficher des informations sur les partages.



=== Boutons de commande

* *Créer un partage*
+
Ouvre la boîte de dialogue Créer un partage qui permet de créer un partage.

* *Créer répertoire d'accueil*
+
Ouvre la boîte de dialogue Créer un partage de répertoire d'accueil, qui permet de créer un nouveau partage de répertoire d'accueil.

* *Modifier*
+
Ouvre la boîte de dialogue Modifier les paramètres, qui permet de modifier les propriétés d'un partage sélectionné.

* *Arrêter le partage*
+
Empêche le partage de l'objet sélectionné.

* * Actualiser*
+
Met à jour les informations dans la fenêtre.





=== Liste des partages

La liste partages affiche le nom et le chemin de chaque partage.

* *Nom de partage*
+
Affiche le nom du partage.

* *Chemin*
+
Affiche le chemin d'accès complet d'un dossier, qtree ou volume existant partagé. Les séparateurs de chemin peuvent être des barres obliques inverses ou des barres obliques inverses, bien que ONTAP affiche tous les séparateurs de chemin sous forme de barres obliques inverses.

* *Répertoire personnel*
+
Affiche le nom du partage du répertoire racine.

* *Commentaire*
+
Affiche des descriptions supplémentaires du partage, le cas échéant.

* *Partage disponible en continu*
+
Indique si le partage est activé pour la disponibilité continue. Depuis la version System Manager 9.6, la disponibilité continue est prise en charge pour les volumes FlexGroup.





=== Zone de détails

La zone située sous la liste partages affiche les propriétés de partage et les droits d'accès pour chaque partage.

* * Propriétés*
+
** Nom
+
Affiche le nom du partage.

** État des oplocks
+
Indique si le partage utilise des verrous opportunistes (oplocks).

** Browsable
+
Indique si le partage peut être consulté par les clients Windows.

** Affiche un instantané
+
Indique si les copies Snapshot peuvent être affichées par les clients.

** Partage disponible en continu
+
Indique si le partage est activé ou désactivé pour la disponibilité continue. Depuis la version System Manager 9.6, la disponibilité continue est prise en charge pour les volumes FlexGroup.

** Énumération basée sur l'accès
+
Indique si l'énumération basée sur l'accès (ABE) est activée ou désactivée sur le partage.

** BranchCache
+
Indique si BranchCache est activé ou désactivé sur le partage.

** Chiffrement SMB
+
Spécifie si le chiffrement des données avec SMB 3.0 est activé au niveau du SVM (Storage Virtual machine) ou au niveau du partage. Si le chiffrement SMB est activé au niveau du SVM, le chiffrement SMB s'applique à tous les partages et la valeur est indiquée comme activé (au niveau du SVM).

** Versions précédentes
+
Indique si les versions précédentes peuvent être affichées et restaurées à partir du client.



* *Partage de contrôle d'accès*
+
Affiche les droits d'accès des utilisateurs du domaine, des groupes de domaines, des utilisateurs locaux et des groupes locaux pour le partage.



*Informations connexes*

xref:task_setting_up_cifs.adoc[Configuration de CIFS]
