---
permalink: online-help-96-97/concept_aggregates.html 
sidebar: sidebar 
keywords: aggregates, system, manager, security, backup, performance, data, sharing, classic, online, help, window 
summary: Vous pouvez utiliser System Manager pour créer des agrégats afin de prendre en charge diverses exigences de sécurité, de sauvegarde, de performance et de partage de données de vos utilisateurs. 
---
= Gérez les agrégats avec System Manager - ONTAP 9.7 et versions antérieures
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Vous pouvez utiliser ONTAP System Manager classique (disponible dans ONTAP 9.7 et versions antérieures) pour créer des agrégats afin de prendre en charge les exigences de sécurité, de sauvegarde, de performance et de partage de données de vos utilisateurs.



== La fenêtre Aggregates

La fenêtre Aggregates permet de créer, d'afficher et de gérer les informations sur les agrégats.



=== Boutons de commande

* *Créer*
+
Ouvre la boîte de dialogue Créer un agrégat, qui permet de créer un agrégat.

* *Modifier*
+
Ouvre la boîte de dialogue Modifier l'agrégat, qui vous permet de modifier le nom d'un agrégat ou le niveau de protection RAID que vous souhaitez fournir à l'agrégat.

* *Supprimer*
+
Supprime l'agrégat sélectionné.

+
[NOTE]
====
Ce bouton est désactivé pour l'agrégat root.

====
* *Plus d'actions*
+
Offre les options suivantes :

* *Changer le statut en*
+
Change le statut de l'agrégat sélectionné à l'un des États suivants :

+
** En ligne
+
L'accès en lecture et en écriture aux volumes contenus dans cet agrégat est autorisé.

** Hors ligne
+
L'accès en lecture et en écriture n'est pas autorisé.

** Limiter
+
Certaines opérations telles que la reconstruction de parité sont autorisées, mais l'accès aux données n'est pas autorisé.



* *Ajouter capacité*
+
Ajout de capacité (disques durs ou SSD) à des agrégats existants

* *Ajouter cache*
+
Permet d'ajouter des disques cache (SSD) aux agrégats HDD existants ou aux agrégats Flash Pool.

+
Ce bouton n'est pas disponible pour un cluster contenant des nœuds qui offrent une personnalité optimisée pour la technologie Flash.

* *Miroir*
+
Permet de mettre en miroir les agrégats.

* *Déplacement de volume*
+
Permet de déplacer un volume FlexVol.

* *Attacher un Tier cloud*
+
Permet d'associer un Tier cloud à l'agrégat.

* * Actualiser*
+
Met à jour les informations dans la fenêtre.





=== Liste d'agrégats

Affiche le nom et les informations d'utilisation de l'espace pour chaque agrégat.

* *Statut*
+
Affiche le statut de l'agrégat.

* *Nom*
+
Affiche le nom de l'agrégat.

* *Nœud*
+
Affiche le nom du nœud sur lequel sont affectés les disques de l'agrégat.

+
Ce champ est disponible uniquement au niveau du cluster.

* *Type*
+
Affiche le type de l'agrégat.

+
Ce champ ne s'affiche pas pour un cluster contenant des nœuds qui ont une personnalité optimisée pour la technologie Flash.

* *Utilisé (%)*
+
Affiche le pourcentage d'espace utilisé dans l'agrégat.

* *Espace disponible*
+
Affiche l'espace disponible dans l'agrégat.

* *Espace utilisé*
+
Affiche la quantité d'espace utilisée pour les données de l'agrégat.

* *Espace total*
+
Affiche l'espace total de l'agrégat.

* *FabricPool*
+
Indique si l'agrégat sélectionné est associé à un Tier cloud.

* *Tier cloud*
+
Si l'agrégat sélectionné est associé à un Tier cloud, il affiche le nom du Tier cloud.

* *Volume Count*
+
Affiche le nombre de volumes associés à l'agrégat.

* *Nombre de disques*
+
Affiche le nombre de disques utilisés pour créer l'agrégat.

* *Flash Pool*
+
Affiche la taille totale de cache de l'agrégat Flash Pool. Une valeur de NA indique que l'agrégat n'est pas un agrégat Flash Pool.

+
Ce champ ne s'affiche pas pour un cluster contenant des nœuds qui ont une personnalité optimisée pour la technologie Flash.

* *Mis en miroir*
+
Indique si l'agrégat est mis en miroir.

* *Type SnapLock*
+
Affiche le type SnapLock de l'agrégat.





=== Zone de détails

Sélectionner un agrégat pour afficher les informations relatives à l'agrégat sélectionné. Vous pouvez cliquer sur Afficher plus de détails pour afficher des informations détaillées sur l'agrégat sélectionné.

* *Onglet vue d'ensemble*
+
Affiche des informations détaillées sur l'agrégat sélectionné et affiche une représentation graphique de l'allocation d'espace de l'agrégat, des économies d'espace de l'agrégat et des performances de l'agrégat en IOPS et des transferts de données totaux.

* *Onglet informations sur le disque*
+
Affiche les informations relatives à la disposition du disque telles que le nom du disque, le type de disque, la taille physique, la taille utilisable, la position du disque, État du disque, nom plex, état plex, groupe RAID, type RAID, et de pool de stockage (le cas échéant) pour l'agrégat sélectionné. Le port de disque associé au chemin primaire du disque et le nom du disque avec le chemin secondaire du disque dans le cadre d'une configuration multivoie sont également affichés.

* *Onglet volumes*
+
Affiche des informations détaillées sur le nombre total de volumes sur l'agrégat, l'espace total de l'agrégat et l'espace attribué à l'agrégat.

* *Onglet performances*
+
Affiche les graphiques qui affichent les mesures de performance des agrégats, y compris le débit et les opérations d'entrée/sortie par seconde. Les données de mesure de performance pour les transferts en lecture, écriture et total sont affichées pour le débit et les IOPS. Les données pour les disques SSD et HDD sont enregistrées séparément.

+
La modification du fuseau horaire du client ou du fuseau horaire du cluster a un impact sur les graphiques de mesures de performance. Vous devez actualiser votre navigateur pour afficher les graphiques mis à jour.



*Informations connexes*

xref:task_provisioning_storage_through_aggregates.adoc[Provisionnement du stockage par le biais d'agrégats]

xref:task_deleting_aggregates.adoc[Suppression d'agrégats]

xref:task_editing_aggregates.adoc[Modification d'agrégats]
