---
permalink: online-help-96-97/concept_rules_for_mixing_disk_types_disk_rpms.html 
sidebar: sidebar 
keywords: rule, online, help, create, aggregate, add, capacity, disk, rpm 
summary: 'Lorsque vous créez un agrégat et que vous ajoutez des disques de capacité à un agrégat, vous devez connaître les règles qui s"appliquent à l"affichage des types de disques et des tours/min des disques.' 
---
= Règles d'affichage des types de disques et du nombre de tours/min des disques dans System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez un agrégat et que vous ajoutez des disques de capacité à un agrégat, vous devez comprendre les règles qui s'appliquent lorsque les types de disques et les tours/min de disque sont affichés dans ONTAP System Manager classique (disponible dans ONTAP 9.7 et versions antérieures).

Lorsque les options de mélange de type de disque et de mélange de RPM de disque ne sont pas activées, le type de disque réel et le nombre réel de tours/min de disque sont affichés.

Lorsque ces options de mélange sont activées, le type de disque effectif et le nombre de tours/min effectif sont affichés au lieu du type de disque réel et du nombre réel de tours/min. Par exemple, lorsque l'option de mélange de disques est activée, System Manager affiche les disques BSA sous FORME DE FSAS. De même, lorsque l'option de mélange des disques RPM est activée, si le régime des disques est de 10 000 et 15 000 tr/min, System Manager affiche le régime effectif à 10 000 tr/min.
