---
permalink: online-help-96-97/concept_how_data_ontap_name_service_switch_configuration_works.html 
sidebar: sidebar 
keywords: ontap, name, service, switch, configuration, works, unix, system, online, help 
summary: 'ONTAP stocke les informations de configuration du service de nom dans une table équivalente au fichier /etc/nsswitch.conf sur les systèmes UNIX. Vous devez connaître les fonctions du tableau et savoir comment ONTAP l"utilise pour que vous puissiez le configurer de façon appropriée pour votre environnement.' 
---
= À propos de la configuration du commutateur de service de nom ONTAP dans System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager Classic (disponible dans ONTAP 9.7 et versions antérieures) stocke les informations de configuration du service de nom dans un tableau équivalent de `/etc/nsswitch.conf` Fichier sur les systèmes UNIX. Vous devez connaître les fonctions du tableau et savoir comment ONTAP l'utilise pour que vous puissiez le configurer de façon appropriée pour votre environnement.

La table commutateur de service de nom ONTAP détermine les sources de service de nom auxquelles ONTAP consulte afin de récupérer les informations relatives à un certain type d'informations de service de nom. ONTAP conserve une table de commutateur de service de noms distincte pour chaque SVM.



== Types de base de données

La table stocke une liste de services de noms distincte pour chacun des types de bases de données suivants :

|===
| Type de base de données | Définit les sources de service de noms pour... | Les sources valides sont... 


 a| 
hôtes
 a| 
Conversion des noms d'hôte en adresses IP
 a| 
fichiers, dns



 a| 
groupe
 a| 
Recherche des informations sur les groupes d'utilisateurs
 a| 
fichiers, nis, ldap



 a| 
passwd
 a| 
Recherche des informations utilisateur
 a| 
fichiers, nis, ldap



 a| 
groupe réseau
 a| 
Recherche des informations de groupe réseau
 a| 
fichiers, nis, ldap



 a| 
carte de nom
 a| 
Mappage des noms d'utilisateur
 a| 
fichiers, ldap

|===


== Types de source

Les sources indiquent quelle source de service de nom utiliser pour récupérer les informations appropriées.

|===
| Spécifiez le type de source... | Pour rechercher des informations dans... | Géré par les familles de commande... 


 a| 
fichiers
 a| 
Fichiers source locaux
 a| 
`vserver services name-service unix-user`

`vserver services name-service unix-group`

`vserver services name-service netgroup`

`vserver services name-service dns hosts`



 a| 
nis
 a| 
Serveurs NIS externes tels que spécifiés dans la configuration de domaine NIS du SVM
 a| 
`vserver services name-service nis-domain`



 a| 
ldap
 a| 
Serveurs LDAP externes comme spécifié dans la configuration du client LDAP du SVM
 a| 
`vserver services name-service ldap`



 a| 
dns
 a| 
Serveurs DNS externes comme spécifié dans la configuration DNS du SVM
 a| 
`vserver services name-service dns`

|===
Même si vous prévoyez d'utiliser NIS ou LDAP pour l'accès aux données et l'authentification d'administration des SVM, vous devez toujours inclure `files` Et configurer des utilisateurs locaux comme un repli en cas d'échec de l'authentification NIS ou LDAP.

*Informations connexes*

xref:task_editing_svm_settings.adoc[Modification des paramètres d'un SVM]
