---
permalink: online-help-96-97/reference_storage_service_definitions.html 
sidebar: sidebar 
keywords: storage, service, definition, online, help, performance, factor 
summary: ONTAP inclut des services de stockage prédéfinis mappés sur les facteurs de performance minimaux correspondants. 
---
= Définitions de service de stockage pour System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager Classic (disponible dans ONTAP 9.7 et versions antérieures) inclut des services de stockage prédéfinis mappés sur des facteurs de performance minimaux correspondants.

L'ensemble réel de services de stockage disponibles dans un cluster ou un SVM est déterminé par le type de stockage qui constitue un agrégat dans la SVM.

Le tableau ci-dessous montre comment les facteurs de performance minimale sont mappés aux services de stockage prédéfinis :

|===
| Service de stockage | IOPS attendues (SLA) | IOPS en pic (SLO) | Nombre minimal d'IOPS pour le volume | Latence estimée | Les IOPS attendues sont-elles appliquées ? 


 a| 
valeur
 a| 
128 par To
 a| 
512 par To
 a| 
75
 a| 
17 ms.
 a| 
Sur AFF: Oui

Sinon : non



 a| 
performances
 a| 
2048 par To
 a| 
4096 par To
 a| 
500
 a| 
2 ms.
 a| 
Oui.



 a| 
extrême
 a| 
6144 par To
 a| 
12288 par To
 a| 
1000
 a| 
1 ms.
 a| 
Oui.

|===
Le tableau ci-dessous définit le niveau de service de stockage disponible pour chaque type de support ou nœud :

|===
| Support ou nœud | Niveau de service du stockage disponible 


 a| 
Disque
 a| 
valeur



 a| 
Disque de machine virtuelle
 a| 
valeur



 a| 
LUN FlexArray
 a| 
valeur



 a| 
Hybride
 a| 
valeur



 a| 
Flash à capacité optimisée
 a| 
valeur



 a| 
Disque SSD (Solid-State Drive) - non AFF
 a| 
valeur



 a| 
Performance optimisée Flash - SSD (AFF)
 a| 
extreme, performance, value

|===