---
permalink: online-help-96-97/task_cloning_nvme_namespace.html 
sidebar: sidebar 
keywords: system, manager, clone, nvme, namespace, nqn, online, help 
summary: 'Vous pouvez utiliser System Manager pour créer rapidement un autre espace de nom de la même configuration en choisissant de cloner un espace de noms. Vous pouvez mapper l"espace de noms nouvellement cloné sur un autre NQN hôte.' 
---
= Clonez un namespace NVMe avec System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ONTAP System Manager Classic (disponible dans ONTAP 9.7 et versions antérieures) pour créer rapidement un autre espace de nom de la même configuration en choisissant de cloner un espace de noms. Vous pouvez mapper l'espace de noms nouvellement cloné sur un autre NQN hôte.

.Avant de commencer
Vous devez disposer d'une licence FlexClone pour cloner un espace de noms.

.Description de la tâche
Vous pouvez cloner un espace de noms avec le mappage d'hôtes sélectionné et l'associer à un autre sous-système.

.Étapes
. Cliquez sur *NVMe* > *NVMe namespaces*.
. Dans la fenêtre *NVMe Namespaces*, sélectionnez l'espace de noms à cloner.
. Vous pouvez renommer le namespace cloné si vous avez besoin d'un nom spécifique, mais qu'il n'est pas nécessaire.
+
La boîte de dialogue fournit un nom par défaut du namespace à cloner.

. Modifier le mappage de sous-système pour l'espace de noms cloné.
. Cliquez sur *OK*.
+
L'espace de noms en ligne mappé est cloné au sein du même SVM avec un nom différent. Le mappage d'hôtes ne sera pas cloné.


