---
permalink: online-help-96-97/task_hiding_snapshot_copy_directory.html 
sidebar: sidebar 
keywords: hide, snapshot, copy, directory, system, manager, online, help 
summary: 'Vous pouvez utiliser System Manager pour masquer le répertoire des copies Snapshot (.snapshot) de sorte que le répertoire des copies Snapshot n"est pas visible lorsque vous affichez les répertoires de vos volumes. Par défaut, le répertoire .snapshot est visible.' 
---
= Masquez le répertoire de copies Snapshot avec System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ONTAP System Manager Classic (disponible dans ONTAP 9.7 et versions antérieures) pour masquer le répertoire des copies Snapshot  `.snapshot`) De sorte que le répertoire de copie Snapshot ne soit pas visible lorsque vous affichez vos répertoires de volumes. Par défaut, le `.snapshot` le répertoire est visible.

.Étapes
. Cliquez sur *Storage* > *volumes*.
. Dans le menu déroulant du champ *SVM*, sélectionnez *tous les SVM*.
. Sélectionnez le volume pour lequel vous souhaitez masquer le répertoire des copies Snapshot.
. Cliquez sur *plus d'actions* > *gérer les instantanés* > *Paramètres de configuration*.
. Assurez-vous que l'option *rendre le répertoire snapshot (.snapshot) visible* n'est pas sélectionnée, puis cliquez sur *OK*.


*Informations connexes*

xref:reference_volumes_window.adoc[Fenêtre volumes]
