---
permalink: online-help-96-97/task_aborting_vault_relationships.html 
sidebar: sidebar 
keywords: abort, snapshot, copy, transfer, online, help, system, manager 
summary: Vous pouvez utiliser System Manager pour abandonner ou arrêter un transfert de données en cours. 
---
= Abandon du transfert d'une copie Snapshot avec System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ONTAP System Manager Classic (disponible dans ONTAP 9.7 et versions antérieures) pour annuler ou arrêter un transfert de données en cours.

.Étapes
. Cliquez sur *protection* > *relations de volume*.
. Sélectionnez la relation pour laquelle vous souhaitez arrêter le transfert de données et cliquez sur *opérations* > *abandonner*.
. Cochez la case *Oui, je souhaite abandonner le transfert* pour confirmer l'opération.
. *Facultatif:* cochez la case *conserver les données partiellement transférées* pour conserver les données qui sont déjà transférées vers le volume de destination.
. Cliquez sur *abandonner*.


.Résultats
L'état du transfert est affiché sous la forme « Aborting » jusqu'à ce que l'opération soit terminée et affichée sous la forme « Idle » après la fin de l'opération.

*Informations connexes*

xref:reference_protection_window.adoc[Fenêtre de protection]
