---
permalink: online-help-96-97/task_updating_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: nondisruptive, upgrades, NDU, cluster, system, manager, online, help 
summary: 'Vous pouvez utiliser System Manager pour mettre à jour un cluster ou des nœuds individuels dans des paires haute disponibilité \(HA\) qui exécutent ONTAP 8.3.1 ou version ultérieure à une version spécifique du logiciel ONTAP sans interrompre l"accès aux données client.' 
---
= Mettez à jour un cluster sans interruption grâce à System Manager - ONTAP 9.7 et version antérieure
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ONTAP System Manager classique (disponible dans ONTAP 9.7 et versions antérieures) pour mettre à jour un cluster ou des nœuds individuels dans des paires haute disponibilité qui exécutent ONTAP 8.3.1 ou version ultérieure d'un logiciel ONTAP spécifique sans interrompre l'accès aux données client.

.Avant de commencer
* Tous les nœuds doivent être en paires haute disponibilité.
* Tous les nœuds doivent être en bon état.
* Vous devez avoir copié l'image logicielle depuis le site de support NetApp vers un serveur HTTP ou FTP sur votre réseau de sorte que les nœuds puissent accéder à l'image.
+
link:task_obtaining_ontap_software_images.html["Obtention d'images du logiciel ONTAP"]



.Description de la tâche
* Si vous essayez d'effectuer d'autres tâches à partir de System Manager lors de la mise à jour du nœud qui héberge la LIF de gestion de cluster, un message d'erreur peut s'afficher.
+
Vous devez attendre la fin de la mise à jour avant d'effectuer toute opération.

* Une mise à jour propagée est effectuée pour les clusters de moins de huit nœuds. Une mise à jour par lot est effectuée pour les clusters de plus de huit nœuds.
+
Dans une mise à jour propagée, les nœuds du cluster sont mis à jour un par un. Dans une mise à jour par lot, plusieurs nœuds sont mis à jour en parallèle.

* Vous pouvez mettre à jour le logiciel ONTAP sans interruption, qu'il s'agisse d'une version à long terme ou d'un service LTS+1.
+
Par exemple, si ONTAP 9.1 et ONTAP 9.3 sont des versions LTS, vous pouvez mettre à jour votre cluster d'ONTAP 9.1 vers ONTAP 9.3 sans interruption.

* Depuis System Manager 9.6, si le protocole NVMe est configuré dans System Manager 9.5 et que vous effectuez une mise à niveau de System Manager 9.5 vers System Manager 9.6, vous n'avez plus de délai de grâce de 90 jours pour que le protocole NVMe soit disponible sans licence. Si la période de grâce est en vigueur lors de la mise à niveau de ONTAP 9.5 vers 9.6, le délai de grâce doit être remplacé par une licence NVMeoF valide pour que vous puissiez continuer à utiliser les fonctionnalités NVMe.
+
Cette fonction n'est pas disponible dans les configurations MetroCluster.

* Si le protocole NVMe n'est pas configuré dans System Manager 9.5 et que vous effectuez une mise à jour de System Manager 9.5 vers System Manager 9.6, la période de grâce n'est pas fournie. Vous devez installer la licence NVMe pour utiliser le protocole NVMe.
+
Cette fonction n'est pas disponible dans les configurations MetroCluster.

* Depuis la version ONTAP 9.5, au moins une LIF NVMe doit être configurée pour chaque nœud d'une paire HA à l'aide du protocole NVMe. Vous pouvez également créer un maximum de deux LIF NVMe par nœud. Lorsque vous effectuez une mise à niveau vers ONTAP 9.5, vous devez vous assurer qu'au moins une LIF NVMe est définie pour chaque nœud d'une paire HA à l'aide du protocole NVMe.


.Étapes
. Cliquez sur *Configuration* > *Cluster* > *Update*.
. Dans l'onglet *Update*, ajoutez une nouvelle image ou sélectionnez une image disponible.
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Ajoutez une nouvelle image logicielle à partir du client local
 a| 
.. Cliquez sur *Ajouter à partir du client local*.
.. Recherchez l'image du logiciel, puis cliquez sur *Ouvrir*.




 a| 
Ajoutez une nouvelle image logicielle depuis le site de support NetApp
 a| 
.. Cliquez sur *Ajouter à partir du serveur*.
.. Dans la boîte de dialogue Add a New Software image, entrez l'URL du serveur HTTP ou du serveur FTP sur lequel vous avez enregistré l'image téléchargée depuis le site de support NetApp.
+
Pour le FTP anonyme, vous devez spécifier l'URL dans le `+ftp://anonymous@ftpserver+` format.

.. Cliquez sur *Ajouter*.




 a| 
Sélectionnez une image disponible
 a| 
Choisissez l'une des images répertoriées.

|===
. Cliquez sur *Validate* pour exécuter les contrôles de validation de pré-mise à jour afin de vérifier si le cluster est prêt pour une mise à jour.
+
L'opération de validation vérifie les composants du cluster pour vérifier que la mise à jour peut être effectuée sans interruption, puis affiche des erreurs ou des avertissements. Elle affiche également toutes les actions correctives requises que vous devez effectuer avant de mettre à jour le logiciel.

+
[NOTE]
====
Vous devez effectuer toutes les actions correctives requises pour les erreurs avant de poursuivre la mise à jour. Bien que vous ne puissiez pas tenir compte des actions correctives associées à ces avertissements, il est conseillé d'effectuer toutes les actions correctives avant de procéder à la mise à jour.

====
. Cliquez sur *Suivant*.
. Cliquez sur *mettre à jour*.
+
La validation est à nouveau effectuée.

+
** Une fois la validation terminée, un tableau affiche toutes les erreurs et tous les avertissements, ainsi que toutes les mesures correctives à prendre avant de poursuivre.
** Si la validation est terminée avec des avertissements, vous pouvez sélectionner la case à cocher *Continuer la mise à jour avec des avertissements*, puis cliquer sur *Continuer*.
Lorsque la validation est terminée et que la mise à jour est en cours, la mise à jour peut être mise en pause en raison d'erreurs. Vous pouvez cliquer sur le message d'erreur pour afficher les détails, puis effectuer les actions correctives avant de reprendre la mise à jour.


+
Une fois la mise à jour terminée, le nœud redémarre et vous êtes redirigé vers la page de connexion de System Manager. Si le redémarrage du nœud est longue, vous devez actualiser votre navigateur.

. Connectez-vous à System Manager et vérifiez que le cluster a bien été mis à jour vers la version sélectionnée en cliquant sur *Configuration* > *Cluster* > *Update* > *Update History*, puis en consultant les détails.


*Informations connexes*

xref:concept_how_you_update_cluster_nondisruptively.adoc[Mettre à niveau un cluster sans interruption]
