---
permalink: online-help-96-97/task_extending_expiry_date_snapshot_copies.html 
sidebar: sidebar 
keywords: extend, expiry, date, snapshot, copy, system, manager, online, help 
summary: 'System Manager peut être utilisé pour étendre la date d"expiration des copies Snapshot d"un volume.' 
---
= Extension de la date d'expiration des copies Snapshot avec System Manager - ONTAP 9.7 et versions antérieures
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager classique (disponible dans ONTAP 9.7 et versions antérieures) peut être utilisé pour étendre la date d'expiration des copies Snapshot d'un volume.

.Avant de commencer
La licence SnapLock doit être installée sur votre système.

.Description de la tâche
Vous pouvez étendre la date d'expiration uniquement pour les copies Snapshot dans un volume de protection des données (DP) qui est le destination d'une relation SnapLock pour SnapVault.

.Étapes
. Cliquez sur *Storage* > *volumes*.
. Dans le menu déroulant du champ *SVM*, sélectionnez *tous les SVM*.
. Sélectionnez un volume.
. Cliquez sur *Afficher plus de détails* pour afficher plus d'informations sur le volume.
. Cliquez sur l'onglet *copies snapshot*.
+
La liste des copies Snapshot disponibles pour le volume sélectionné s'affiche.

. Sélectionnez la copie Snapshot à modifier, puis cliquez sur *prolonger la date d'expiration*.
. Dans la boîte de dialogue *prolonger la date d'expiration*, spécifiez la date d'expiration.
+
Ces valeurs doivent être comprises entre 1 jour et 70 ans, voire infinies.

. Cliquez sur *OK*.

