---
permalink: online-help-96-97/task_accessing_cluster_by_using_system_manager_by_using_browser.html 
sidebar: sidebar 
keywords: online, help, access, cluster, ontap, system, manager, graphic, interface, cli, command, line, interface 
summary: 'Si vous préférez utiliser une interface graphique plutôt que l"interface de ligne de commandes pour l"accès et la gestion d"un cluster, vous pouvez utiliser ONTAP System Manager, inclus avec ONTAP en tant que service Web, activé par défaut et accessible via un navigateur.' 
---
= Accès à un cluster via l'interface graphique basée sur un navigateur de ONTAP System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous préférez utiliser une interface graphique plutôt que l'interface de ligne de commandes pour l'accès et la gestion d'un cluster, vous pouvez utiliser ONTAP System Manager, inclus avec ONTAP en tant que service Web, activé par défaut et accessible via un navigateur.

.Avant de commencer
* Vous devez disposer d'un compte utilisateur de cluster configuré avec `admin` rôle et le `http`, `ontapi`, et `console` types d'applications.
* Les cookies et les données du site doivent être activés dans le navigateur.


.Description de la tâche
Vous pouvez utiliser une LIF de cluster management ou un LIF de node management pour accéder à ONTAP System Manager. Pour un accès ininterrompu à ONTAP System Manager, vous devez utiliser une LIF de gestion du cluster.

.Étapes
. Pointez le navigateur Web vers l'adresse IP de la LIF de cluster management :
+
** Si vous utilisez IPv4 : `+https://cluster-mgmt-LIF+`
** Si vous utilisez IPv6 : `https://[cluster-mgmt-LIF]`
Seul le protocole HTTPS est pris en charge pour l'accès au navigateur de ONTAP System Manager.


+
Si le cluster utilise un certificat numérique auto-signé, il est possible que le navigateur affiche un avertissement indiquant que le certificat n'est pas approuvé. Vous pouvez accepter le risque de continuer l'accès ou installer un certificat numérique signé par l'autorité de certification sur le cluster pour l'authentification du serveur.

. Si vous avez configuré une bannière d'accès à l'aide de l'interface de ligne de commande, lisez le message affiché dans la boîte de dialogue *Avertissement* et choisissez l'option requise pour continuer.
+
Cette option n'est pas prise en charge sur les systèmes sur lesquels l'authentification SAML (Security assertion Markup Language) est activée.

+
** Si vous ne souhaitez pas continuer, cliquez sur *Annuler*, puis fermez le navigateur.
** Si vous souhaitez continuer, cliquez sur *OK* pour accéder à la page de connexion de ONTAP System Manager.


. Connectez-vous à ONTAP System Manager à l'aide des identifiants de l'administrateur du cluster.


*Informations connexes*

https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"]
