---
permalink: nfs-config-esxi/task_verifying_configuration_is_supported.html 
sidebar: sidebar 
keywords: reliable, operation, verify, configuration, support, nfs, verify that the configuration is supported 
summary: Pour un fonctionnement fiable, vous devez vérifier que la configuration complète est prise en charge. Le répertorie les configurations prises en charge pour NFS et pour Virtual Storage Console. 
---
= Vérifiez que la configuration est prise en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour un fonctionnement fiable, vous devez vérifier que la configuration complète est prise en charge. Le répertorie les configurations prises en charge pour NFS et pour Virtual Storage Console.

.Étapes
. Accédez au pour vérifier que vous disposez d'une combinaison prise en charge des composants suivants :
+
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

+
** Logiciel ONTAP
** Protocole de stockage NFS
** Version du système d'exploitation ESXi
** Type et version du système d'exploitation invité
** Pour le logiciel (VSC)
** Plug-in NFS pour VAAI


. Cliquez sur le nom de la configuration sélectionnée.
+
Les détails de cette configuration s'affichent dans la fenêtre Détails de la configuration.

. Vérifiez les informations dans les onglets suivants :
+
** Remarques
+
Le répertorie les alertes et informations importantes spécifiques à votre configuration.

** Politiques et lignes directrices
+
Recommandations générales pour toutes les configurations NAS.




