---
permalink: fc-config-esxi/task_updating_hba_firmware.html 
sidebar: sidebar 
keywords: fc, host, bus, adapter, hba, esx, support, driver, firmware, bio, update, update the hba driver firmware and bios 
summary: 'Si les adaptateurs bus hôte FC de l"hôte ESX n"exécutent pas les versions de pilote, de micrologiciel et de BIOS prises en charge, vous devez les mettre à jour.' 
---
= Mettez à jour le pilote HBA, le micrologiciel et le BIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si les adaptateurs de bus hôte FC (HBA) de l'hôte ESX n'exécutent pas les versions de pilote, de micrologiciel et de BIOS prises en charge, vous devez les mettre à jour.

.Avant de commencer
Vous devez avoir identifié les versions de pilote, de micrologiciel et de BIOS prises en charge pour votre configuration à partir du https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"].

.Description de la tâche
Les pilotes, micrologiciels, BIOS et utilitaires HBA sont fournis par les fournisseurs HBA.

.Étapes
. Répertorie les versions du pilote HBA, du micrologiciel et du BIOS installés à l'aide des commandes de la console hôte VMware ESXi correspondant à votre version d'ESXi.
. Téléchargez et installez le nouveau pilote, le nouveau micrologiciel et le nouveau BIOS, selon les besoins, à partir du site d'assistance du fournisseur de l'adaptateur HBA.
+
Les instructions d'installation et tous les utilitaires d'installation requis sont disponibles avec le téléchargement.


