---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: 'Vous pouvez rapidement configurer le service FC sur une machine virtuelle de stockage, provisionner une LUN et mettre la LUN à disposition à l"aide d"un adaptateur de bus hôte FC sur un serveur Red Hat Enterprise Linux.' 
---
= Présentation de la configuration FC pour Red Hat Enterprise Linux
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rapidement configurer le service FC sur une machine virtuelle de stockage (SVM), provisionner une LUN et mettre celle-ci à disposition à l'aide d'un adaptateur de bus hôte FC (HBA) sur un serveur Red Hat Enterprise Linux à l'aide de l'interface classique ONTAP System Manager (ONTAP 9.7 et versions antérieures).

Utilisez cette procédure pour configurer le service FC sur un SVM si :

* L'hôte exécute une version prise en charge de Red Hat Enterprise Linux 6.4 ou ultérieure.
* Vous utilisez des HBA et des commutateurs FC traditionnels.
+

NOTE: La technologie FCoE (Fibre Channel over Ethernet) n'est pas couverte par cette procédure.

* Vous disposez d'au moins deux ports FC target disponibles sur chaque nœud du cluster.
Les ports FC et UTA2 intégrés (également appelés « CNA »), ainsi que certains adaptateurs, sont configurables. La configuration de ces ports s'effectue sur l'interface de ligne de commande ONTAP, et n'est pas traitée dans cette procédure.
* Vous ne configurez pas le démarrage SAN FC.


Si ces hypothèses ne sont pas correctes pour votre situation, vous devez consulter les ressources suivantes :

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["Administration SAN"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["Configuration SAN"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Installation de Linux Unified Host Utilities 7.1"^]




== D'autres façons de le faire dans ONTAP

|===


| Pour effectuer ces tâches avec... | Reportez-vous à... 


| System Manager redessiné (disponible avec ONTAP 9.7 et versions ultérieures) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Provisionnement du stockage SAN pour les serveurs Linux"^] 


| Interface de ligne de commande ONTAP | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Workflow de configuration de LUN avec l'interface de ligne de commandes"^] 
|===