---
permalink: fc-config-rhel/task_discovering_new_scsi_devices_dm_multipath_devices.html 
sidebar: sidebar 
keywords: lun, storage, cluster, linux, host, scsi, device, i/o, dm-multipath, aggregate, device, multipath, automatic, rescan, discover new scsi device luns and multipath device 
summary: 'Les LUN du cluster de stockage apparaissent sur l"hôte Linux comme des périphériques SCSI, qui sont des chemins d"E/S que DM-Multipath rassemble dans un nouveau périphérique, appelé périphérique multichemin. L"hôte ne détecte pas automatiquement les nouveaux périphériques SCSI (LUN) que vous ajoutez à votre système. Vous devez les réanalyser manuellement pour les détecter.' 
---
= Découvrir les nouveaux périphériques SCSI (LUN) et les chemins d'accès multiples
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les LUN du cluster de stockage apparaissent sur l'hôte Linux comme des périphériques SCSI, qui sont des chemins d'E/S que DM-Multipath rassemble dans un nouveau périphérique, appelé périphérique multichemin. L'hôte ne détecte pas automatiquement les nouveaux périphériques SCSI (LUN) que vous ajoutez à votre système. Vous devez les réanalyser manuellement pour les détecter.

.Avant de commencer
Vous devez disposer d'une copie du `rescan` script, qui est dans le `sg3_utils` Package faisant partie de votre distribution Linux OS.

.Étapes
. Détecter les nouveaux périphériques SCSI (LUN) et créer les périphériques multivoie correspondants pour les LUN : `/usr/bin/rescan-scsi-bus.sh`
. Vérifiez la configuration DM-Multipath :
+
`multipath -ll`

+
Ce résultat affiche le type de résultat suivant, répertoriant les paramètres recommandés pour chaque LUN NetApp :

+
[listing]
----
3600a0980324666546e2b443251655177 dm-2 NETAPP,LUN C-Mode
size=10G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:1:0 sdb 8:16  active ready  running
| |- 0:0:0:0 sda 8:0   active ready  running
| |- 1:0:0:0 sde 8:64  active ready  running
| `- 1:0:1:0 sdf 8:80  active ready  running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:3:0 sdd 8:48  active ready  running
  |- 1:0:3:0 sdh 8:112 active ready  running
  |- 0:0:2:0 sdc 8:32  active ready  running
  `- 1:0:2:0 sdg 8:96  active ready  running
----

