---
permalink: fc-config-rhel/task_installing_linux_unified_host_utilities_optimizing_i_o_performance.html 
sidebar: sidebar 
keywords: linux, unified, host, utilities, software, sanlun, utility, netapp, lun, report, tool, display, information, storage, cluster, node, bus, adapter, hba, correct, server, profile, linux, optimize, performance, install linux unified host utilities and optimize i/o performance 
summary: 'Linux Unified Host Utilities inclut l"utilitaire sanlun, un outil de création de rapports LUN NetApp qui permet d"afficher des informations sur les nœuds de cluster de stockage et les adaptateurs de bus hôte qui se trouvent sur l"hôte Linux.' 
---
= Installation des utilitaires d'hôtes unifiés Linux et optimisation des performances d'E/S.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel Linux Unified Host Utilities inclut `sanlun` Utilitaire, outil de création de rapports LUN NetApp que vous pouvez utiliser pour afficher des informations sur le nodescluster de stockage et les adaptateurs bus hôte (HBA) situés sur l'hôte Linux. Vous devez également activer le profil de serveur correct sur l'hôte Linux pour optimiser les performances du stockage NetApp.

.Avant de commencer
Vous devez avoir identifié la version de Linux Unified Host Utilities prise en charge pour votre configuration à l'aide de la matrice d'interopérabilité. Vous devez également avoir le `tuned` Qui fait partie de votre distribution Linux OS et contient le `tuned-adm` commande, que vous utilisez pour définir le profil de serveur sur l'hôte.

.Étapes
. Téléchargez la version Linux Unified Host Utilities prise en charge sur le site de support NetApp.
+
http://mysupport.netapp.com/NOW/cgi-bin/software["Téléchargements NetApp : logiciels"]

. Installez le logiciel Linux Unified Host Utilities en suivant les instructions de la documentation d'installation.
. Si le `tuned` le pack n'est pas installé, entrez la commande suivante :``yum install tuned``
. Pour un hôte physique, vérifiez que vous avez défini le `enterprise-storage` profil : `tuned-adm profile enterprise-storage`
. Pour un hôte virtuel, assurez-vous que vous avez défini le `virtual-guest` profil : `tuned-adm profile virtual-guest`
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Installation de Linux Unified Host Utilities 7.1"]


