---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: 'À l"aide de l"interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures), vous pouvez configurer rapidement l"accès SMB/CIFS à un nouveau volume sur un serveur virtuel de stockage nouveau ou existant (SVM)' 
---
= Présentation de la configuration SMB/CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À l'aide de l'interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures), vous pouvez configurer rapidement l'accès SMB/CIFS à un nouveau volume sur un nouveau serveur virtuel de stockage ou sur un serveur virtuel de stockage existant.

Utilisez cette procédure pour configurer l'accès à un volume de la manière suivante :

* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Votre réseau de données utilise l'IPspace par défaut, le domaine de diffusion par défaut et le groupe de basculement par défaut.
+
Si votre réseau de données est plat, l'utilisation de ces objets par défaut garantit que les LIFs basculeront correctement en cas de panne de liaison. Si vous n'utilisez pas les objets par défaut, reportez-vous à la https://docs.netapp.com/us-en/ontap/networking/index.html["Documentation de gestion du réseau"^] Pour plus d'informations sur la configuration du basculement de chemin LIF.

* Les autorisations d'accès au fichier NTFS seront utilisées pour sécuriser le nouveau volume.


Pour plus d'informations sur la plage de fonctionnalités du protocole SMB de ONTAP, consultez le link:https://docs.netapp.com/us-en/ontap/smb-admin/index.html["Présentation des références SMB"^].



== D'autres façons de le faire dans ONTAP

|===


| Pour effectuer ces tâches avec... | Reportez-vous à... 


| System Manager redessiné (disponible avec ONTAP 9.7 et versions ultérieures) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html["Provisionnement du stockage NAS pour les serveurs Windows avec SMB"^] 


| Interface de ligne de commande ONTAP | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html["Présentation de la configuration SMB avec l'interface de ligne de commande"^] 
|===