---
permalink: fc-config-windows/task_verifying_that_iscsi_fc_configuration_is_supported.html 
sidebar: sidebar 
keywords: reliable, operation, verify, entire, fc, configuration, support, verify that the fc configuration is support 
summary: Pour un fonctionnement fiable, vous devez vérifier que la configuration FC complète est prise en charge. 
---
= Vérifiez que la configuration FC est prise en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour un fonctionnement fiable, vous devez vérifier que la configuration FC complète est prise en charge.

.Étapes
. Accédez à la matrice d'interopérabilité pour vérifier que vous disposez d'une combinaison de composants prise en charge :
+
** Logiciel ONTAP
** Architecture UC de l'ordinateur hôte (pour serveurs en rack standard)
** Modèle de lame de processeur spécifique (pour serveurs lames)
** Modèle d'adaptateur de bus hôte FC (HBA), versions de pilote, de micrologiciel et de BIOS
** Protocole de stockage (FC)
** Version du système d'exploitation Windows
** Utilitaires d'hôtes unifiés Windows


. Cliquez sur le nom de la configuration sélectionnée.
+
Les détails de cette configuration s'affichent dans la fenêtre Détails de la configuration.

. Vérifiez les informations dans les onglets suivants :
+
** Remarques
+
Le répertorie les alertes et informations importantes spécifiques à votre configuration.

+
Passez en revue les alertes pour identifier les correctifs requis pour votre système d'exploitation.

** Politiques et lignes directrices
+
Présente des recommandations générales pour toutes les configurations SAN.




