---
permalink: expansion/concept_configuring_node_management_lifs.html 
sidebar: sidebar 
keywords: controller, module, physical, install, power, configure, node-mangement, lif, configure node-management lifs 
summary: Une fois les modules de contrôleur physiquement installés, vous pouvez les mettre sous tension et configurer leur LIF de node-management. 
---
= Configuration des LIF node-management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois les modules de contrôleur physiquement installés, vous pouvez les mettre sous tension et configurer leur LIF de node-management.

.Description de la tâche
Vous devez effectuer cette procédure sur les deux nœuds.

.Étapes
. Accédez au module de contrôleur via la console série.
. Mettez le module de contrôleur sous tension et attendez que le nœud démarre et que l'assistant de configuration du cluster démarre automatiquement sur la console.
+
[listing]
----
Welcome to the cluster setup wizard.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the cluster setup wizard.
   Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value.
----
. Suivez les invites de l'assistant web d'installation du cluster pour configurer une LIF de gestion des nœuds à l'aide des informations de mise en réseau que vous avez recueillies précédemment.
. Type `exit` Une fois la configuration LIF de node management terminée, quittez l'assistant d'installation et terminez les tâches d'administration.
+
[listing]
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the command line interface:
exit
----
. Connectez-vous au nœud en tant que `admin` utilisateur, qui ne nécessite pas de mot de passe.
+
[listing]
----
Tue Mar 4 23:13:33 UTC 2015
login: admin
******************************************************
* This is a serial console session. Output from this *
* session is mirrored on the SP console session.     *
----
. Répétez l'ensemble de la procédure pour le deuxième module de contrôleur nouvellement installé.

