---
permalink: expansion/task_ensuring_hardware_level_ha_is_enabled.html 
sidebar: sidebar 
keywords: install, controller, module, reuse, maintenance, mode, ha, state, hardware-level, enable, ensure hardware-level ha is enabled 
summary: 'Si les nouveaux modules de contrôleur installés sont réutilisés (pas nouveaux), vous devez passer en mode maintenance et vérifier que leur état de haute disponibilité est défini sur HA.' 
---
= Assurez-vous que la haute disponibilité au niveau matériel est activée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si les nouveaux modules de contrôleur installés sont réutilisés - pas de nouveau --vous devez passer en mode maintenance et vérifier que leur état de haute disponibilité est défini sur HA.

.Description de la tâche
Si vous utilisez de nouveaux modules de contrôleur, vous pouvez ignorer cette procédure, car la haute disponibilité est activée par défaut. Dans le cas contraire, vous devez effectuer cette procédure sur les deux nœuds.

.Étapes
. Sur le premier nœud, entrez en mode maintenance :
+
.. Quittez le nodeshell en entrant `halt`.
+
L'invite DU CHARGEUR s'affiche.

.. Entrer en mode Maintenance `boot_ontap maint`.
+
Après l'affichage de certaines informations, l'invite du mode maintenance s'affiche.



. En mode Maintenance, vérifiez que le module de contrôleur et le châssis sont en état HA :
+
.. Affichez l'état HA du module de contrôleur et du châssis en saisissant l'emplacement `ha-config show`.
.. Si l'état affiché du contrôleur n'est pas `HA`, entrez `ha-config modify controller ha`.
.. Si l'état affiché du châssis n'est pas `HA`, entrez `ha-config modify chassis ha`.
.. Vérifiez que la haute disponibilité est activée sur le module de contrôleur et le châssis en saisissant le point `ha-config show`.


. Retour à ONTAP :
+
.. Entrez `halt` Pour quitter le mode Maintenance.
.. Démarrez ONTAP en saisissant `boot_ontap`
.. Attendez que le nœud démarre et que l'assistant de configuration du cluster démarre automatiquement sur la console.
.. Appuyez quatre fois sur entrée pour accepter les paramètres existants de la LIF de node-management.
.. Connectez-vous au nœud en tant que `admin` utilisateur, qui ne nécessite pas de mot de passe.


. Répétez cette procédure sur l'autre nœud que vous ajoutez au cluster.

