---
permalink: expansion/task_backing_up_cluster_configuration.html 
sidebar: sidebar 
keywords: expand, cluster, advance, privilege, backup, file, configuration, information, back up the cluster configuration 
summary: 'Avant de développer un cluster, vous devez utiliser le privilège avancé pour créer un fichier de sauvegarde afin d"enregistrer les informations de configuration du cluster et éventuellement enregistrer les configurations du nœud.' 
---
= Sauvegarder la configuration du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de développer un cluster, vous devez utiliser le privilège avancé pour créer un fichier de sauvegarde afin d'enregistrer les informations de configuration du cluster et éventuellement enregistrer les configurations du nœud.

.Étapes
. Définissez le niveau de privilège sur avancé à l'aide du `set -privilege advanced` commande.
. Créez un fichier de sauvegarde de la configuration du cluster à l'aide du `system configuration backup create` commande avec `-backup-type cluster` paramètre.
+
[listing]
----
cluster1::*> system configuration backup create -node cluster1-1 -backup-name clusterbeforeexpansion.7z -backup-type cluster
[Job 5573] Job is queued: Cluster Backup OnDemand Job.
----
. Créez un fichier de sauvegarde de la configuration de chaque nœud à l'aide du `system configuration backup create` commande avec `-backup-type node` paramètre pour chaque nœud.
. Faites revenir le niveau de privilège à admin en utilisant le `set -privilege admin` commande.

