---
permalink: volume-restore-snapvault/task_verifying_restore_operation.html 
sidebar: sidebar 
keywords: perform, restore, operation, snapvault, backup, destination, volume, verify, source cluster, verify the restore operation 
summary: 'Une fois l"opération de restauration effectuée à partir du volume de destination de sauvegarde SnapVault, vous devez vérifier l"état de l"opération de restauration sur le cluster source.' 
---
= Vérifiez l'opération de restauration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois l'opération de restauration effectuée à partir du volume de destination de sauvegarde SnapVault, vous devez vérifier l'état de l'opération de restauration sur le cluster source.

.Description de la tâche
Vous devez effectuer cette tâche à partir du cluster *source*.

.Étapes
. Accédez à la fenêtre *volumes*.
. Sélectionnez le volume source dans la liste volumes et effectuez l'une des opérations suivantes, en fonction de la version de ONTAP :
+
** Depuis ONTAP 9.3 : double-cliquez sur le volume source pour afficher les détails, puis sur *PROTECTION* pour identifier le volume de destination dans la relation SnapMirror et le nom de la SVM qui contient le volume.
** ONTAP 9.2 ou version antérieure : cliquez sur l'onglet *Data protection* en bas pour identifier le volume de destination dans la relation SnapMirror et le nom de la SVM qui contient le volume.
Le champ Type s'affiche `Restore` temporairement. Une fois l'opération de restauration terminée, le champ s'affiche `Vault`.
+
Vous devez résoudre tous les problèmes liés aux relations SnapVault. Les procédures de dépannage pour les relations SnapMirror sont également applicables aux relations SnapVault.

+
http://www.netapp.com/us/media/tr-4015.pdf["Rapport technique NetApp 4015 : configuration de SnapMirror et meilleures pratiques pour ONTAP 9.1, 9.2"^]




