---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: nfs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: 'Vous pouvez rapidement configurer l"accès NFS à un nouveau volume sur une machine virtuelle de stockage (SVM) nouvelle ou existante à l"aide de l"interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures).' 
---
= Présentation de la configuration NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rapidement configurer l'accès NFS à un nouveau volume sur une machine virtuelle de stockage (SVM) nouvelle ou existante à l'aide de l'interface classique de ONTAP System Manager (ONTAP 9.7 et versions antérieures).

Utilisez cette procédure pour configurer l'accès à un volume de la manière suivante :

* L'accès NFS sera NFS via NFS v3, et non NFS V4 ou NFS v4.1.
* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Votre réseau de données utilise l'IPspace par défaut, le domaine de diffusion par défaut et le groupe de basculement par défaut.
+
Si votre réseau de données est plat, l'utilisation de ces objets par défaut garantit que les LIFs basculeront correctement en cas de panne de liaison. Si vous n'utilisez pas les objets par défaut, reportez-vous à la section https://docs.netapp.com/us-en/ontap/networking/index.html["Documentation de gestion de réseau"^] Pour plus d'informations sur la configuration du basculement de chemin LIF.

* Les autorisations liées au fichier UNIX seront utilisées pour sécuriser le nouveau volume.
* Le cas échéant, LDAP est fourni par Active Directory.


Pour plus d'informations sur la plage de fonctionnalités du protocole NFS ONTAP, consultez le link:https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["Présentation de référence NFS"^].



== D'autres façons de le faire dans ONTAP

|===


| Pour effectuer ces tâches avec... | Reportez-vous à... 


| System Manager redessiné (disponible avec ONTAP 9.7 et versions ultérieures) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_linux_nfs.html["Provisionnement du stockage NAS pour les serveurs Linux via NFS"^] 


| Interface de ligne de commande ONTAP | link:https://docs.netapp.com/us-en/ontap/nfs-config/index.html["Présentation de la configuration NFS avec l'interface de ligne de commande"^] 
|===