---
permalink: nfs-config/task_deciding_where_to_provision_new_volume.html 
sidebar: sidebar 
keywords: create, nfs, volume, exist, storage, virtual, machine, svm, configuration, workflow, decide where to provision the new volume 
summary: 'Avant de créer un nouveau volume NFS, vous devez décider si vous souhaitez le placer dans une machine virtuelle de stockage (SVM) existante et, le cas échéant, le volume de configuration nécessaire à la SVM. Cette décision détermine votre flux de travail.' 
---
= Choisissez l'emplacement de provisionnement du nouveau volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un nouveau volume NFS, vous devez décider si vous souhaitez le placer dans une machine virtuelle de stockage (SVM) existante et, le cas échéant, le volume de configuration nécessaire à la SVM. Cette décision détermine votre flux de travail.



== Procédure

* Si vous souhaitez provisionner un volume sur un nouveau SVM, créez un nouveau SVM compatible NFS.
+
link:task_creating_protocol_enabled_svm.html["Création d'un nouveau SVM compatible NFS"]

+
Vous devez choisir cette option si NFS n'est pas activé sur un SVM existant.

* Si vous souhaitez provisionner un volume sur un SVM existant sur lequel NFS est activé mais non configuré, configurez l'accès NFS sur le SVM existant.
+
link:task_configuring_access_to_existing_svm.html["Configuration de l'accès NFS sur un SVM existant"]

+
C'est le cas si vous n'avez pas suivi cette procédure pour créer le SVM lors de la configuration d'un autre protocole.

* Si vous souhaitez provisionner un volume sur un SVM existant entièrement configuré pour l'accès NFS, ajoutez un volume NFS à la SVM compatible NFS.
+
link:concept_adding_protocol_volume_to_protocol_enabled_svm.html["Ajout d'un volume NFS à un SVM compatible NFS"]


